### ISSUE TITLE
Please search for open bugs

### ISSUE THREAD

**Issue by asarubbo** [toralf/tinderbox#3]
Hello,

as suggested on irc time ago, please search for open bugs. The issue here is that the bug is filed always when there isn't a bug that contains the summary in the way you are formatting it.

Example:
https://bugs.gentoo.org/759376 (sci-libs/geos-3.9.0 : QA Notice: Unrecognized configure options:)
https://bugs.gentoo.org/759295 (sci-libs/geos-3.9.0: Unrecognized configure options: --disable-python --disable-ruby)

The current approach is valid when the bugs are filed from only one people.
Thanks

**Comment by toralf** [comment]
query logic for b.g.o. was factored out into its own script at the beginning of december.
Bug searching has now to be made immediately before filing a bug and is no longer done automatically at the time where an issue happened.

**Comment by asarubbo** [comment]
https://bugs.gentoo.org/764935 and https://bugs.gentoo.org/764935 is a recent example
