### ISSUE TITLE
support v2 cgroups

### ISSUE THREAD

**Issue by telans** [toralf/tinderbox#4]
v2 cgroups are present on systemd systems. Currently, cgroup.sh doesn't work as the rules it calls are specific to v1 cgroups.

libcgroup HEAD currently supports modifying necessary v2 cgroup options: https://github.com/libcgroup/libcgroup

For my case I just removed cgroup references, but it would be nice if this was supported. Low priority I'm sure, so I might take a crack at adding it.

**Comment by toralf** [comment]
Commit fa2f4c42c addresses the issue if v1 is not available.
For v2 a pull request is appreciated :-)
FWIW I do use openRC only and therefore cannot test systemd cgroup v2 logic.

**Comment by telans** [comment]
Thanks for adding the check. Hopefully I'll get around to it soon
