### ISSUE TITLE
Increase size of title

### ISSUE THREAD

**Issue by asarubbo** [toralf/tinderbox#6]
I noticed that the title is 'cutted' at 150 chars:

https://github.com/toralf/tinderbox/blob/d7aa56199f82beac7ba3d4811e2d00e3c454e6a0/bin/job.sh#L515

I tested it a while ago and discover that the limit for our bugzilla is 254, so would be great have a bigger value, thanks.

**Comment by toralf** [comment]
I tend to not change such a value as long as devs do not complain about them.

**Comment by toralf** [comment]
Well, actually increased it to 170 in commit 3f308d339 two months ago.
